POST http://localhost:8081/account
Content-Type: application/json

{
  "accountId": "admin",
  "accountPwd": "1234",
  "accountName": "정승우",
  "accountEmail": "tkdltlf@naver.com",
  "accountStatus": "가입"
}

###
GET http://localhost:8081/account


###
GET http://localhost:8080/account/by/tkdltlf@naver.com



###
GET http://localhost:8080/account/tkdltlf3



###
POST http://localhost:8080/account/tkdltlf3/withdrawal


###
DELETE http://localhost:8080/account/tkdltlf3


